<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Configuration">
    <PlatformToolset Condition="'$(PlatformToolset)' == '' And '$(VisualStudioVersion)' &gt;= '18.0'">v145</PlatformToolset>
    <PlatformToolset Condition="'$(PlatformToolset)' == ''">v143</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
    <UseDebugLibraries Condition="'$(Configuration)' == 'Debug'">true</UseDebugLibraries>
    <UseDebugLibraries Condition="'$(Configuration)' != 'Debug'">false</UseDebugLibraries>
    <PreferredToolArchitecture>x64</PreferredToolArchitecture>
  </PropertyGroup>
</Project>