#pragma once

#define LEMONSQUASH_VERSION_MAJOR 2
#define LEMONSQUASH_VERSION_MINOR 0
#define LEMONSQUASH_VERSION_PATCH 0
#define LEMONSQUASH_VERSION_REVISION 5
#define LEMONSQUASH_VERSION_POSTFIX "r5"

#define LEMONSQUASH_VERSION_NUMBERS \
    LEMONSQUASH_VERSION_MAJOR, LEMONSQUASH_VERSION_MINOR, LEMONSQUASH_VERSION_PATCH, LEMONSQUASH_VERSION_REVISION

#define LEMONSQUASH_VERSION_STRINGIFY_IMPL(value) #value
#define LEMONSQUASH_VERSION_STRINGIFY(value) LEMONSQUASH_VERSION_STRINGIFY_IMPL(value)
#define LEMONSQUASH_VERSION_STRING \
    LEMONSQUASH_VERSION_STRINGIFY(LEMONSQUASH_VERSION_MAJOR) "." \
    LEMONSQUASH_VERSION_STRINGIFY(LEMONSQUASH_VERSION_MINOR) "." \
    LEMONSQUASH_VERSION_STRINGIFY(LEMONSQUASH_VERSION_PATCH)
#define LEMONSQUASH_VERSION_WSTRING L"" LEMONSQUASH_VERSION_STRING

#define LEMONSQUASH_VERSION_FILE_STRING \
    LEMONSQUASH_VERSION_STRING "." LEMONSQUASH_VERSION_STRINGIFY(LEMONSQUASH_VERSION_REVISION)
